import jsPDF from "jspdf";
import type { AuditResult } from "./types";

const COLOR = {
  black: "#2a2b29",
  blue: "#b8d3d8",
  blueDark: "#6b9ba4",
  bluePale: "#e0ecee",
  fluro: "#e1ff01",
  beige: "#f7f5ee",
  taupe: "#bfc0b6",
  red: "#ef4444",
};

function urlPath(url: string): string {
  try {
    return new URL(url).pathname || "/";
  } catch {
    return url;
  }
}

interface PageContext {
  doc: jsPDF;
  W: number;
  H: number;
  M: number;
  y: number;
  pageNum: number;
}

function newPage(ctx: PageContext, opts: { showFooter?: boolean } = {}): void {
  if (opts.showFooter !== false) drawFooter(ctx);
  ctx.doc.addPage();
  ctx.pageNum++;
  ctx.doc.setFillColor(COLOR.beige);
  ctx.doc.rect(0, 0, ctx.W, ctx.H, "F");
  ctx.y = 60;
  drawHeader(ctx);
}

function drawHeader(ctx: PageContext): void {
  const { doc, W, M } = ctx;
  doc.setFillColor(COLOR.black);
  doc.rect(0, 0, W, 30, "F");
  doc.setTextColor(COLOR.beige);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("WLDM.IO  ·  HARMONIC CENTRALITY", M, 19);
  doc.setFont("helvetica", "normal");
  doc.text(`p. ${ctx.pageNum}`, W - M, 19, { align: "right" });
}

function drawFooter(ctx: PageContext): void {
  const { doc, W, H, M } = ctx;
  doc.setTextColor(COLOR.taupe);
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text("Generated by WLDM.IO Harmonic Centrality Analyzer", M, H - 20);
  doc.text("wldm.io", W - M, H - 20, { align: "right" });
}

function ensureSpace(ctx: PageContext, needed: number): void {
  if (ctx.y + needed > ctx.H - 60) newPage(ctx);
}

function drawSectionTitle(ctx: PageContext, title: string): void {
  const { doc, W, M } = ctx;
  ensureSpace(ctx, 50);
  doc.setTextColor(COLOR.black);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(title, M, ctx.y);
  ctx.y += 8;
  doc.setDrawColor(COLOR.black);
  doc.setLineWidth(2);
  doc.line(M, ctx.y, W - M, ctx.y);
  ctx.y += 18;
}

function drawSubTitle(ctx: PageContext, text: string): void {
  ensureSpace(ctx, 30);
  ctx.doc.setTextColor(COLOR.blueDark);
  ctx.doc.setFont("helvetica", "bold");
  ctx.doc.setFontSize(12);
  ctx.doc.text(text, ctx.M, ctx.y);
  ctx.y += 16;
}

function drawParagraph(ctx: PageContext, text: string, opts: { color?: string; size?: number } = {}): void {
  const { doc, W, M } = ctx;
  doc.setTextColor(opts.color ?? COLOR.black);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(opts.size ?? 10);
  const lines = doc.splitTextToSize(text, W - 2 * M);
  ensureSpace(ctx, lines.length * 14 + 8);
  doc.text(lines, M, ctx.y);
  ctx.y += lines.length * 14 + 8;
}

function drawCallout(ctx: PageContext, label: string, body: string, bg: string): void {
  const { doc, W, M } = ctx;
  doc.setFontSize(10);
  const lines = doc.splitTextToSize(body, W - 2 * M - 24);
  const h = lines.length * 14 + 30;
  ensureSpace(ctx, h + 12);
  doc.setFillColor(bg);
  doc.setDrawColor(COLOR.black);
  doc.setLineWidth(1);
  doc.roundedRect(M, ctx.y, W - 2 * M, h, 8, 8, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(COLOR.black);
  doc.text(label.toUpperCase(), M + 12, ctx.y + 16);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(lines, M + 12, ctx.y + 28);
  ctx.y += h + 14;
}

export async function generateAuditPdf(result: AuditResult): Promise<void> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 40;
  const ctx: PageContext = { doc, W, H, M, y: 0, pageNum: 1 };
  const { analysis, domain } = result;

  // ─── COVER ────────────────────────────────────────────────────────
  doc.setFillColor(COLOR.beige);
  doc.rect(0, 0, W, H, "F");
  doc.setFillColor(COLOR.black);
  doc.rect(0, 0, W, 60, "F");
  doc.setTextColor(COLOR.beige);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("WLDM.IO  ·  HARMONIC CENTRALITY", M, 36);

  doc.setTextColor(COLOR.black);
  doc.setFontSize(38);
  doc.text("Internal Link", M, 180);
  doc.text("Architecture Audit", M, 220);

  doc.setFillColor(COLOR.fluro);
  doc.setDrawColor(COLOR.black);
  doc.setLineWidth(1);
  doc.setFontSize(20);
  const dW = doc.getTextWidth(domain) + 30;
  doc.roundedRect(M, 250, dW, 38, 8, 8, "FD");
  doc.text(domain, M + 15, 277);

  // KPI summary
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  let kx = M;
  const kw = (W - 2 * M - 30) / 4;
  const kpis = [
    ["Pages crawled", String(analysis.totalPages)],
    ["Internal links", String(analysis.totalLinks)],
    ["Orphan pages", String(analysis.orphans.length)],
    ["Crawl time", `${(result.elapsedMs / 1000).toFixed(1)}s`],
  ];
  kpis.forEach(([label, value], i) => {
    const bg = i === 2 && analysis.orphans.length > 0 ? COLOR.fluro : "#ffffff";
    doc.setFillColor(bg);
    doc.setDrawColor(COLOR.black);
    doc.roundedRect(kx, 320, kw, 70, 8, 8, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(COLOR.black);
    doc.text(value, kx + 12, 358);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(COLOR.taupe);
    doc.text(label.toUpperCase(), kx + 12, 375);
    kx += kw + 10;
  });

  // What this report contains
  doc.setTextColor(COLOR.black);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Inside this report", M, 430);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(COLOR.black);
  const toc = [
    "1. Headline findings & priority recommendations",
    "2. Authority distribution & tier breakdown",
    "3. Top pages by harmonic centrality",
    "4. Click depth from homepage",
    "5. Orphan pages — discoverable to humans, invisible to Google",
    "6. URL clusters",
    "7. Methodology & how to read these scores",
  ];
  let tocY = 450;
  toc.forEach((line) => {
    doc.text(line, M, tocY);
    tocY += 16;
  });

  // Cover footer
  doc.setTextColor(COLOR.taupe);
  doc.setFontSize(8);
  const today = new Date().toLocaleDateString("en-US", { day: "numeric", month: "long", year: "numeric" });
  doc.text(`Generated ${today}  ·  WLDM.IO`, M, H - 30);
  doc.text(result.startUrl, W - M, H - 30, { align: "right" });

  // ─── PAGE: HEADLINE FINDINGS ──────────────────────────────────────
  newPage(ctx);
  drawSectionTitle(ctx, "Headline findings");
  drawParagraph(
    ctx,
    `We crawled ${analysis.totalPages} pages on ${domain} and built a directed graph of ${analysis.totalLinks} internal links. Below are the most important things we found, ordered by impact on your SEO.`,
    { color: COLOR.taupe }
  );

  if (analysis.diagnostics.recommendations.length === 0) {
    drawCallout(
      ctx,
      "All clear",
      "No critical issues detected. Your internal link architecture looks healthy on the metrics we track. Use the per-section data on the following pages to spot opportunities for further consolidation.",
      COLOR.bluePale
    );
  } else {
    analysis.diagnostics.recommendations.forEach((rec, i) => {
      const bg = i === 0 ? COLOR.fluro : COLOR.blue;
      drawCallout(ctx, `Finding #${i + 1}`, rec, bg);
    });
  }

  // ─── DIAGNOSTICS BLOCK ────────────────────────────────────────────
  ensureSpace(ctx, 200);
  drawSubTitle(ctx, "Site diagnostics");

  const diagRows: Array<[string, string, string]> = [
    [
      "Homepage rank in HC",
      analysis.diagnostics.homepageRank
        ? `#${analysis.diagnostics.homepageRank} of ${analysis.totalPages}`
        : "Not detected",
      analysis.diagnostics.homepageRank && analysis.diagnostics.homepageRank <= 5
        ? "OK — homepage sits at the top of your link graph as expected."
        : "Concerning — healthy sites usually rank the homepage in the top 3.",
    ],
    [
      "HC distribution",
      analysis.diagnostics.hcCompressed ? "Compressed" : "Healthy",
      analysis.diagnostics.hcCompressed
        ? "Most pages have similar HC — your site lacks a clear authority hierarchy."
        : "Long-tail distribution — a few high-authority hubs and many specialist pages.",
    ],
    [
      "PageRank concentration",
      analysis.diagnostics.pagerankDegenerate ? "Uniform (no concentration)" : "Differentiated",
      analysis.diagnostics.pagerankDegenerate
        ? "Likely a small or fully connected site. Add more discriminating links."
        : "PageRank is doing real work to identify your most authoritative pages.",
    ],
    [
      "Graph density",
      analysis.density.toFixed(3),
      analysis.density > 0.05
        ? "Densely connected — pages reach each other easily."
        : "Sparsely connected — pages are far apart in the graph.",
    ],
  ];
  diagRows.forEach(([label, value, expl]) => {
    ensureSpace(ctx, 50);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(COLOR.black);
    doc.text(label, M, ctx.y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLOR.blueDark);
    doc.text(value, M + 180, ctx.y);
    doc.setTextColor(COLOR.taupe);
    doc.setFontSize(9);
    const lines = doc.splitTextToSize(expl, W - 2 * M);
    doc.text(lines, M, ctx.y + 13);
    ctx.y += 13 + lines.length * 12 + 8;
  });

  // ─── PAGE: TIER BREAKDOWN ─────────────────────────────────────────
  newPage(ctx);
  drawSectionTitle(ctx, "Authority tiers");
  drawParagraph(
    ctx,
    "Pages are bucketed into three tiers based on harmonic centrality — how reachable each page is across the whole graph. High-tier pages capture most of your internal link equity.",
    { color: COLOR.taupe }
  );

  const tiers = { high: 0, medium: 0, low: 0 };
  analysis.nodes.forEach((nd) => tiers[nd.tier]++);
  const tierTotal = Math.max(analysis.totalPages, 1);
  // Visual bar
  const barY = ctx.y;
  const barW = W - 2 * M;
  const segH = 28;
  const segs: Array<[string, number, string]> = [
    ["HIGH", tiers.high, COLOR.fluro],
    ["MEDIUM", tiers.medium, COLOR.blue],
    ["LOW", tiers.low, "#ffffff"],
  ];
  let xCursor = M;
  segs.forEach(([label, count, color]) => {
    const w = (count / tierTotal) * barW;
    if (w > 0) {
      doc.setFillColor(color);
      doc.setDrawColor(COLOR.black);
      doc.rect(xCursor, barY, w, segH, "FD");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(COLOR.black);
      if (w > 60) doc.text(`${label} ${count}`, xCursor + 8, barY + 18);
    }
    xCursor += w;
  });
  ctx.y += segH + 14;

  drawCallout(
    ctx,
    "How to read tiers",
    `${tiers.high} high-authority pages capture most of your internal link equity. ${tiers.low} low-tier pages — many of which are orphans or dead-ends — are silently bleeding crawl budget. Move attention from the bottom 25% to the top 25%.`,
    COLOR.bluePale
  );

  // ─── PAGE: TOP PAGES ──────────────────────────────────────────────
  newPage(ctx);
  drawSectionTitle(ctx, "Top pages by harmonic centrality");
  drawParagraph(
    ctx,
    "Higher HC = closer to all other pages = more crawl budget, more link equity, more AI citation probability. These are the rooms guests walk through most often.",
    { color: COLOR.taupe }
  );

  ensureSpace(ctx, 30);
  // Table header
  doc.setFillColor(COLOR.blue);
  doc.rect(M, ctx.y, W - 2 * M, 22, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(COLOR.black);
  doc.text("#", M + 8, ctx.y + 14);
  doc.text("PATH", M + 30, ctx.y + 14);
  doc.text("HC", W - M - 200, ctx.y + 14);
  doc.text("PR", W - M - 130, ctx.y + 14);
  doc.text("DEPTH", W - M - 80, ctx.y + 14);
  doc.text("IN/OUT", W - M - 30, ctx.y + 14);
  ctx.y += 26;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  analysis.topPages.slice(0, 30).forEach((node, i) => {
    ensureSpace(ctx, 20);
    doc.setTextColor(COLOR.taupe);
    doc.text(String(i + 1), M + 8, ctx.y);
    doc.setTextColor(COLOR.black);
    const path = urlPath(node.url).slice(0, 50);
    doc.text(path, M + 30, ctx.y);

    // Mini HC bar
    const barXLocal = W - M - 200;
    const hcBarW = 50;
    doc.setDrawColor(COLOR.black);
    doc.setFillColor(COLOR.bluePale);
    doc.rect(barXLocal, ctx.y - 7, hcBarW, 8, "FD");
    doc.setFillColor(COLOR.blueDark);
    doc.rect(barXLocal, ctx.y - 7, hcBarW * node.harmonic, 8, "F");
    doc.setFontSize(8);
    doc.setTextColor(COLOR.black);
    doc.text(node.harmonic.toFixed(2), barXLocal + hcBarW + 4, ctx.y);

    doc.setFontSize(9);
    doc.text(node.pagerank.toFixed(4), W - M - 130, ctx.y);
    doc.text(node.depth >= 0 ? String(node.depth) : "—", W - M - 80, ctx.y);
    doc.text(`${node.inDegree}/${node.outDegree}`, W - M - 30, ctx.y);
    ctx.y += 18;
  });

  // ─── PAGE: CLICK DEPTH ────────────────────────────────────────────
  newPage(ctx);
  drawSectionTitle(ctx, "Click depth from homepage");
  drawParagraph(
    ctx,
    "How many clicks from the homepage to reach each page (BFS over the link graph). Google's crawler doesn't run forever — pages more than 3-4 clicks deep get crawled and re-crawled less often.",
    { color: COLOR.taupe }
  );

  // Depth chart as text bars
  const maxCount = Math.max(...analysis.depthHistogram.map((d) => d.count), 1);
  const chartW = W - 2 * M - 100;
  analysis.depthHistogram.forEach((d) => {
    ensureSpace(ctx, 20);
    const label = d.depth === -1 ? "unreachable" : d.depth === 0 ? "homepage" : `${d.depth} click${d.depth === 1 ? "" : "s"}`;
    doc.setTextColor(COLOR.black);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(label, M, ctx.y);
    const w = (d.count / maxCount) * chartW;
    doc.setDrawColor(COLOR.black);
    const color = d.depth === -1 ? COLOR.red : d.depth === 0 ? COLOR.fluro : d.depth <= 3 ? COLOR.blueDark : COLOR.taupe;
    doc.setFillColor(color);
    doc.rect(M + 90, ctx.y - 8, w, 11, "FD");
    doc.setFontSize(9);
    doc.setTextColor(COLOR.black);
    doc.text(String(d.count), M + 95 + w, ctx.y);
    ctx.y += 16;
  });
  ctx.y += 6;

  const deepCount = analysis.nodes.filter((nd) => nd.depth > 3).length;
  if (deepCount > 0) {
    drawCallout(
      ctx,
      "Action",
      `${deepCount} page${deepCount === 1 ? "" : "s"} sit${deepCount === 1 ? "s" : ""} more than 3 clicks from the homepage. Add links to these from a higher-traffic hub (your blog index, footer, or related-content widget).`,
      COLOR.fluro
    );
  } else {
    drawCallout(
      ctx,
      "Healthy",
      "All pages reachable within 3 clicks — Google should have no trouble indexing your site.",
      COLOR.bluePale
    );
  }

  // ─── PAGE: ORPHANS ────────────────────────────────────────────────
  if (analysis.orphans.length > 0) {
    newPage(ctx);
    drawSectionTitle(ctx, "Orphan pages");
    drawParagraph(
      ctx,
      `${analysis.orphans.length} page${analysis.orphans.length === 1 ? "" : "s"} have zero internal links pointing to them. They exist on your site but are invisible to Google's crawler, AI assistants, and human navigation.`,
      { color: COLOR.taupe }
    );
    drawCallout(
      ctx,
      "Why this matters",
      "Orphan pages don't accrue link equity, don't get re-crawled often, and rarely show up in AI citations. Each orphan is wasted SEO real estate.",
      COLOR.fluro
    );
    ensureSpace(ctx, 30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(COLOR.black);
    doc.text("Orphan list", M, ctx.y);
    ctx.y += 16;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    analysis.orphans.slice(0, 80).forEach((o) => {
      ensureSpace(ctx, 16);
      doc.setTextColor(COLOR.black);
      const path = urlPath(o.url).slice(0, 80);
      doc.text(`•  ${path}`, M, ctx.y);
      ctx.y += 14;
    });
  }

  // ─── PAGE: CLUSTERS ───────────────────────────────────────────────
  newPage(ctx);
  drawSectionTitle(ctx, "URL clusters");
  drawParagraph(
    ctx,
    "Pages grouped by their first URL path segment. Tells you which sections of the site capture the most authority.",
    { color: COLOR.taupe }
  );

  const clusterMap = new Map<string, { count: number; avgHC: number; topUrl: string; topHC: number }>();
  analysis.nodes.forEach((nd) => {
    const c = clusterMap.get(nd.cluster) ?? { count: 0, avgHC: 0, topUrl: "", topHC: 0 };
    c.count++;
    c.avgHC += nd.harmonic;
    if (nd.harmonic > c.topHC) {
      c.topHC = nd.harmonic;
      c.topUrl = nd.url;
    }
    clusterMap.set(nd.cluster, c);
  });
  const clusters = [...clusterMap.entries()]
    .map(([name, c]) => ({ name, ...c, avgHC: c.avgHC / Math.max(c.count, 1) }))
    .sort((a, b) => b.avgHC - a.avgHC);

  ensureSpace(ctx, 30);
  doc.setFillColor(COLOR.blue);
  doc.rect(M, ctx.y, W - 2 * M, 22, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(COLOR.black);
  doc.text("CLUSTER", M + 8, ctx.y + 14);
  doc.text("PAGES", M + 180, ctx.y + 14);
  doc.text("AVG HC", M + 240, ctx.y + 14);
  doc.text("TOP PAGE", M + 310, ctx.y + 14);
  ctx.y += 26;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  clusters.slice(0, 25).forEach((c) => {
    ensureSpace(ctx, 16);
    doc.setTextColor(COLOR.black);
    doc.text(`/${c.name}`, M + 8, ctx.y);
    doc.text(String(c.count), M + 180, ctx.y);
    doc.text(c.avgHC.toFixed(2), M + 240, ctx.y);
    doc.text(urlPath(c.topUrl).slice(0, 35), M + 310, ctx.y);
    ctx.y += 14;
  });

  // ─── METHODOLOGY ─────────────────────────────────────────────────
  newPage(ctx);
  drawSectionTitle(ctx, "Methodology & how to read these scores");

  drawSubTitle(ctx, "How we crawled");
  drawParagraph(
    ctx,
    `Started at ${result.startUrl} and followed internal links breadth-first up to ${analysis.totalPages} pages. We use a real Chrome User-Agent and fall back to a residential proxy on Cloudflare-style anti-bot blocks (${result.proxyUsed} of ${result.totalRequests} requests went via proxy).`
  );

  drawSubTitle(ctx, "Harmonic centrality");
  drawParagraph(
    ctx,
    "H(v) = Σ 1/d(v,u) for all reachable u ≠ v. The sum of inverse shortest-path distances. High HC = page is close to many other pages = more crawl budget and link equity flow."
  );

  drawSubTitle(ctx, "PageRank");
  drawParagraph(
    ctx,
    "Google's original algorithm. A page's authority is the weighted sum of authorities of pages linking to it. We use damping = 0.85."
  );

  drawSubTitle(ctx, "Betweenness centrality");
  drawParagraph(
    ctx,
    "How often a page sits on the shortest path between other pages. High betweenness = bottleneck or hub. Removing such pages would fragment the graph."
  );

  drawSubTitle(ctx, "HITS hub & authority scores");
  drawParagraph(
    ctx,
    "Pages can be hubs (pointing to many good pages) and authorities (pointed at by many hubs). Healthy sites have both — clear hubs in your navigation, clear authorities at the leaves."
  );

  drawSubTitle(ctx, "Tiers");
  drawParagraph(
    ctx,
    "Top 25% by HC = high authority. Bottom 25% = low. Pages with zero incoming links are flagged as orphans regardless of tier."
  );

  drawFooter(ctx);

  // Save
  const safeDomain = domain.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "");
  const date = new Date().toISOString().slice(0, 10);
  doc.save(`harmonic-${safeDomain}-${date}.pdf`);
}
